language: python
sudo: false
install:
  - make
script:
  - make lint
  - py.test .
deploy:
  provider: pypi
  user: getsentry
  password:
    secure: "ykVZDrx7o93lr9ZyG2rGTDoOmZXoGZygSK+Hl20gNkGfZt1YCWu5I5uO0zt62pJjzUoxkpm43N/+tzcYza1rRwcrukaKVNYXI9f7zYoQj9Oa3UgT7a7FosAfF42I63LR4Ic/kul6G5TECVjCshONy5JKunk+KHj+SO/speXyCzkTXRmc39dAE3p3Hn9t774A45dENRt6lX3/aUTMZGjG8wHWanJ9tF17IKTv7NiKD96OZtGM9YnF+RcN6/sNpeJqh2y9u3uUiJhrnsBpo56HVrupDrSttZ+pq5wAOd4FlGBh4LBtKhmDmUT+HBk4d1BL1kK/zkHDggthmbjwiIfIEXcq3V5Nstkfr/hKfPDs60iTlQEsI1NjmksrLnnh5Gy8AjET72IQplsZZiJ7UxUL0MJ11/ZSdbK9ttuE12fyabLNzNqrRvz3kjuJK/MWHjvoaQegEHBEKPkSw67mimGcq+nwzOTJmsZRVWLV3+hGyc+wM3tv1E03cu9RQisJm0JVG4Gwst8H1AhyMSmDgxSoch4adxepvqK5gq2DJjNs529rHUjMw+ilierU/aPvGYmFNo2DfYKrKRJ7OMMy433/lfEMYZN2unH6emM4QDRL5/50JZeyTtFiasBRfD75D5ry9Nfj0yATq8RKm7H2dGm1VQfeWUSzAJc5DclLs5clofE="
  on:
    tags: true
  distributions: sdist bdist_wheel
matrix:
  fast_finish: true
  include:
    - python: 2.7
      install:
        - make
    - python: 2.7
      install:
        - pip install pytest==2.5
        - make
    - python: 3.6
      install:
        - pip install pytest==3.5
        - make
    - python: 3.6
      install:
        - make
